[package]
name = "fuse_runtime_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version  = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
uuid = "1.18.1"
fuse_runtime_window = { path = "../window" }
anyhow = "1.0.100"
